spring:
  application:
    name: class-graphql
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      inspection:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

grpc:
  client:
    playback-service:
      address: 'discovery:///playback-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    payment-service:
      address: 'discovery:///enrollment-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    enrollment-service:
      address: 'discovery:///enrollment-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

