spring:
  application:
    name: class-discovery

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    registry:
      default-open-for-traffic-count: 0 # 0?? ??? ?? ?? Replication ??? ?? (??? 1)
  client:
    # replication ??? ?? registerWithEureka, fetchRegistry? true? ??
    registerWithEureka: true # ?????? ??? ????? ?? ?? (??? true)
    fetchRegistry: true # ?????? ?? ??? ????? ?? ?? (??? true), 30??? Eureka Client ? ??? ????? ?? ?? ?? ???
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  # Renews Threshold => ?? heartbeat ? (??? 30?) * Instance ? + Spring ?? ???? ?? Instance ? (1) * renewal-percent-threshold ? ?? ? ???? ??.
  # ex: 2 * 1 + 1 * 0.85 = 3
  # Renews (last min) => ?? heartbeat ? (??? 30?) * Instance ?
  # ex: 2 * 1 = 2
  server:
    renewal-percent-threshold: 0.85 # ? ?? ?? ?? heartbeat ? ???? ? ??
    enable-self-preservation: true # ???? ???? ??? ?? ??? ?? ?? ?? ?? ?? ?? (????? true ??)